print "commit1"
print "commit2"
print "change file1.py"
print "commit3"
print "comit4"
print "commit1 on new-feature branch"
print "git commit --amend"
print "git commit 1 on new-feature "
print "commit2 on new-feature"